title: Gnaneswari Giridharagopalan  # your name (or website title) here
logo: ""C:\Users\deepa\Desktop\Meenu.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Python Connoisseur
  <br><br>
  Data Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/mai-elhadad-591123b8/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
